# Generated by Django 4.2.20 on 2025-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_alter_devicelocation_floorplan_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="fuzzy",
            field=models.BooleanField(
                default=False, help_text="Based on last public ip reported, not precise"
            ),
        ),
    ]
